server:
  listen: 8080
  workers: 4

  upstream:
    - id: node1
      url: jsonplaceholder.typicode.com
    - id: node2
      url: www.dhruvwebdev.tech
    - id: node3
      url: localhost:8002

  headers:
    - key: x-forward-for
      value: "$ip"  # Ensure this is processed at runtime
    - key: Authorization
      value: "Bearer $token"  # Ensure this is processed at runtime

  rules:
    - path: /todos
      upstream:
        - node1
        - node2
    - path: /
      upstream:
        - node2
    - path: /static
      upstream:
        - node1
        - node2
        - node3
